name: Manage AKS Pods

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select the action to perform'
        required: true
        type: choice
        options:
          - 'deploy'
          - 'clean'
          - 'start'
          - 'stop'
          - 'stop-loadgen'
          - 'start-loadgen'
          - 'run-script'  # Added option to run script
      manifest:
        description: 'Select the Kubernetes manifest file to deploy'
        default: 'easytravel-frontend'
        type: choice
        options:
          - 'easytravel-backend'
          - 'easytravel-config'
          - 'easytravel-frontend'
          - 'easytravel-loadgen'
          - 'easytravel-mongodb-secret'
          - 'easytravel-mongodb'
          - 'easytravel-nginx'
          - 'loadgen'
      namespace:
        description: 'Specify the namespace to deploy to'
        required: true
        default: 'easytravel'
        type: choice
        options:
          - 'easytravel'
          - 'argocd'

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Setup Kubernetes
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG_DATA" | base64 -d > ~/.kube/config

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ env.KUBE_CONFIG_DATA }}

      - name: Perform Action
        run: |
          if [ "${{ github.event.inputs.action }}" == "deploy" ]; then
            kubectl apply -f ${{ github.workspace }}/manifests/${{ github.event.inputs.manifest }}.yaml -n ${{ github.event.inputs.namespace }}
          elif [ "${{ github.event.inputs.action }}" == "clean" ]; then
            kubectl delete deployment ${{ github.event.inputs.manifest }} -n ${{ github.event.inputs.namespace }}
          elif [ "${{ github.event.inputs.action }}" == "stop" ]; then
            kubectl -n ${{ github.event.inputs.namespace }} scale --replicas=0 deployment/${{ github.event.inputs.manifest }}
          elif [ "${{ github.event.inputs.action }}" == "start" ]; then
            kubectl -n ${{ github.event.inputs.namespace }} scale --replicas=1 deployment/${{ github.event.inputs.manifest }}
          elif [ "${{ github.event.inputs.action }}" == "start-loadgen" ]; then
            kubectl apply -f ${{ github.workspace }}/manifests/easytravel-config.yaml -n ${{ github.event.inputs.namespace }}
            kubectl apply -f ${{ github.workspace }}/manifests/easytravel-loadgen.yaml -n ${{ github.event.inputs.namespace }}
          elif [ "${{ github.event.inputs.action }}" == "stop-loadgen" ]; then
            kubectl -n ${{ github.event.inputs.namespace }} scale --replicas=0 deployment/loadgen
          elif [ "${{ github.event.inputs.action }}" == "run-script" ]; then
            bash ${{ github.workspace }}/scripts/create_easytravel.sh
          else
            echo "Invalid action specified"
            exit 1
          fi
